# Generated by Django 4.2.1 on 2023-05-23 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_planner', '0002_team_teamtouser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название Встречи')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meeting_to_team', to='meeting_planner.team', verbose_name='Команда')),
            ],
        ),
    ]
