# Generated by Django 4.2.1 on 2023-05-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting_planner', '0004_userfreetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='day',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='День недели'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='end_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Конец встречи'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='start_date_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Начало встречи'),
        ),
        migrations.DeleteModel(
            name='UserFreeTime',
        ),
    ]
